import '../services.css';
export function AI() {
  return (
    <div>
      <img src="/ai.avif" alt="environment" className="ServiceImage" />
      <div>
        <div className="MainServiceHero">AI & Machine Learning</div>
        <div className="MainServicePage">
          Nanosat Ai is engaged by an international consortium of
          governments and environmental organizations to develop a
          next-generation geospatial intelligence platform focused on
          large-scale environmental monitoring and prediction. The consortium is
          struggling with massive volumes of fragmented data coming from
          satellites, IoT sensors, climate models, and historical land-use
          records. Traditional GIS tools provide descriptive insights, but they
          fall short when it comes to real-time analysis, forecasting, and
          decision support at a global scale. <br />
          <br />
          To address this, Nanosat Ai builds an AI-first geospatial
          platform that deeply integrates machine learning at every layer of the
          system. Advanced deep learning models automatically ingest and
          harmonize multi-source satellite imagery—including optical, radar, and
          hyperspectral data—despite differences in resolution, frequency, and
          quality. Self-supervised learning techniques detect cloud cover,
          sensor anomalies, and missing data, ensuring that the spatial datasets
          remain accurate and continuously updated without heavy manual
          intervention. <br /> <br />
          Machine learning models are then applied to extract high-value
          insights from this fused geospatial data. Convolutional neural
          networks identify land-cover changes such as deforestation, urban
          expansion, and water body shrinkage, while temporal models analyze
          patterns over time to distinguish natural seasonal variation from
          human-driven disruption. These models continuously retrain using new
          satellite passes and field data, allowing the system to adapt as
          environmental conditions evolve. <br />
          <br />
          Building on this foundation, Nanosat Ai introduces
          predictive intelligence using advanced AI techniques. Spatio-temporal
          forecasting models predict future risks such as wildfire spread, flood
          probability, drought severity, and biodiversity loss weeks or even
          months in advance. Reinforcement learning is used to simulate
          intervention strategies—such as controlled burns, conservation zoning,
          or water-release planning—and evaluate their potential outcomes before
          any real-world action is taken. <br />
          <br />
          Finally, the insights generated by the platform are delivered through
          an interactive geospatial interface powered by AI-driven analytics.
          Decision-makers can ask natural-language questions—such as “Which
          regions are at highest ecological risk in the next 90 days?”—and
          receive visual, map-based answers supported by confidence scores and
          model explanations. By combining geospatial expertise with large-scale
          AI and machine learning, Nanosat Ai enables its clients to
          move from reactive monitoring to proactive, data-driven environmental
          stewardship.
        </div>
      </div>
    </div>
  );
}
